name: Build app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build python3-pip libxi-dev -y
          pip3 install meson
          
      - name: Create build dir
        run: meson build

      - name: Ninja Build
        run: |
          cd build
          ninja -j$(nproc --all)
      
      - uses: actions/upload-artifact@v2
        with:
          name: NESZ-linux-x86_64
          path: build/NESZ

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
            msystem: MINGW64
            update: true
      - name: Install dependencies
        run: pacman -S --noconfirm --needed ninja mingw-w64-x86_64-{meson,toolchain}
          
      - name: Create build dir
        run: meson build
      
      - name: Ninja Build
        run: |
          cd build
          ninja -j$(nproc --all)

      - uses: actions/upload-artifact@v2
        with:
          name: NESZ-windows-x86_64
          path: build/NESZ.exe
