name: Linux Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        working-directory: ${{runner.workspace}}
        run: |
          sudo apt update
          sudo apt install cmake ninja-build qt5-default libsdl2-dev
          
      - name: Create build dir
        working-directory: ${{runner.workspace}}
        run: mkdir ${{runner.workspace}}/build

      - name: Configure cmake
        working-directory: ${{runner.workspace}}/build
        run: cmake ${{runner.workspace}} -G Ninja -D BUILD_TESTS=OFF
      
      - name: Ninja Build
        working-directory: ${{runner.workspace}}/build
        run: |
          ninja
      
      - uses: actions/upload-artifact@v1
        with:
          name: NESZ-linux-x86_64
          path: ${{runner.workspace}}/build/bin
