name: Build app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build python3-pip libxi-dev -y
          pip3 install meson
          
      - name: Create build dir
        run: meson build

      - name: Ninja Build
        run: |
          ninja -j$(nproc --all) -C build/
      
      - uses: actions/upload-artifact@v2
        with:
          name: NESZ-linux-x86_64
          path: build/NESZ

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install dependencies
        run: pip install meson ninja
          
      - name: Create build dir
        run: meson build
      
      - name: Ninja Build
        run: |
          ninja -C build/

      - uses: actions/upload-artifact@v2
        with:
          name: NESZ-windows-x86_64
          path: build/NESZ.exe
