name: Unit Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson ninja-build libsdl2-dev -y
        
      - name: Create build dir
        run: meson build -D build_tests=true
      
      - name: Build and Test
        run: |
          cd build
          GTEST_COLOR=1 ninja test -v
