name: Unit Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        working-directory: ${{runner.workspace}}
        run: |
          sudo apt update
          sudo apt install meson ninja-build libsdl2-dev
        
      - name: Create build dir
        working-directory: ${{runner.workspace}}
        run: meson build -D build_tests=true
      
      - name: Build Test
        working-directory: ${{runner.workspace}}/build
        run: |
          GTEST_COLOR=1 meson test -v
